# action.yml
name: 'hubr'
description: 'hubr release'
inputs:
  name:
    description: 'the name of the project'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}
