# action.yml
name: 'hubr'
description: 'hubr release'
inputs:
  name:
    description: 'the name of the project'
    required: true
  from:
    description: 'the VERSION file to read from'
    default: 'VERSION'
  token:
    description: 'the github api token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_API_TOKEN: ${{ inputs.token }}
  args:
    - ${{ inputs.name }}
outputs:
  version:
    description: 'the version that was released'
